esphome:
  name: esp_sprinkler_controller
  platform: ESP32
  board: featheresp32
  includes: esp_sprinkler.h
  on_boot:
  #   priority: 500
    then:
      # - lambda: 'esp_sprinkler::setup();'
      - script.execute: display_on

wifi:
  ssid: "abcde12345"
  password: abcde12345"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "esp_sprinkler_controller"
    password: "W81pKxXbMA5c"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API and define services
api:
  password: "abcde12345"
  services:
    - service: set_display_page
      variables:
        page: int
      then:
        - lambda: 'esp_sprinkler::set_display_page(page);'
    - service: set_run_times
      variables:
        zone_1: int
        zone_2: int
        zone_3: int
        zone_4: int
        zone_5: int
      then:
        - globals.set:
            id: zone_1_run_time
            value: !lambda 'return zone_1;'
        - globals.set:
            id: zone_2_run_time
            value: !lambda 'return zone_2;'
        - globals.set:
            id: zone_3_run_time
            value: !lambda 'return zone_3;'
        - globals.set:
            id: zone_4_run_time
            value: !lambda 'return zone_4;'
        - globals.set:
            id: zone_5_run_time
            value: !lambda 'return zone_5;'
        - component.update: main_lcd
    - service: set_run_time_multiplier
      variables:
        multiplier: float
      then:
        - globals.set:
            id: zone_run_time_multiplier
            value: !lambda 'return multiplier;'
        - component.update: main_lcd

ota:
  password: "abcde12345"

globals:
  # zone run times (in minutes)
  - id: zone_1_run_time
    type: int
    restore_value: yes
    initial_value: '10'
  - id: zone_2_run_time
    type: int
    restore_value: yes
    initial_value: '30'
  - id: zone_3_run_time
    type: int
    restore_value: yes
    initial_value: '5'
  - id: zone_4_run_time
    type: int
    restore_value: yes
    initial_value: '25'
  - id: zone_5_run_time
    type: int
    restore_value: yes
    initial_value: '15'
  # zone run time multiplier
  - id: zone_run_time_multiplier
    type: float
    restore_value: yes
    initial_value: '1'
  # currently active zone
  - id: active_zone
    type: int
    restore_value: no
    initial_value: '-1'
  # currently active zone time remaining
  - id: seconds_remaining
    type: int
    restore_value: no
    initial_value: '-1'
  # selected display pages/items
  - id: selected_display_page
    type: int
    restore_value: no
    initial_value: '0'
  - id: selected_display_item
    type: int
    restore_value: no
    initial_value: '0'
  # last processed encoder value
  - id: encoder_value
    type: int
    restore_value: no
    initial_value: '0'

script:
  # display screen management
  - id: button_press
    mode: restart
    then:
      - script.execute: display_on
      - delay: 60s
      - lambda: 'esp_sprinkler::set_display_page(esp_sprinkler::DisplayPageEnum::MAIN_SCREEN);'
  # display power management
  - id: display_on
    mode: restart
    then:
      - lambda: 'id(main_lcd)->turn_on();'
      - delay: 120s
      - lambda: 'id(main_lcd)->turn_off();'
  # switches all zones off
  - id: all_zones_off
    mode: restart
    then:
      - switch.turn_off: esp_sprinkler_controller_triac_zone_1
      - switch.turn_off: esp_sprinkler_controller_triac_zone_2
      - switch.turn_off: esp_sprinkler_controller_triac_zone_3
      - switch.turn_off: esp_sprinkler_controller_triac_zone_4
      - switch.turn_off: esp_sprinkler_controller_triac_zone_5
      - switch.turn_off: esp_sprinkler_controller_triac_zone_6
      - switch.turn_off: esp_sprinkler_controller_triac_zone_7

interval:
  - interval: 1s
    then:
      - lambda: 'esp_sprinkler::run_time_count_down();'
      
status_led:
  pin:
    number: GPIO5
    inverted: true

time:
  - platform: homeassistant
    id: esptime

i2c:
  id: i2c_bus
  frequency: 400kHz
  sda: 21
  scl: 22

mcp23017:
  - id: mcp23017_hub
    address: 0x20

spi:
  clk_pin: GPIO14
  mosi_pin: GPIO13
  miso_pin: GPIO12

binary_sensor:
  - platform: status
    id: esp_sprinkler_controller_api_status
    name: "Dev Sprinkler Controller API Status"
  # - platform: gpio
  #   id: esp_sprinkler_controller_sd_cd
  #   name: "Sprinkler Controller SD CD"
  #   pin:
  #     mcp23017: mcp23017_hub
  #     number: 14
  #     mode: INPUT_PULLUP
  # - platform: gpio
  #   id: esp_sprinkler_controller_tmp117_alert
  #   name: "Sprinkler Controller TMP117 Alert"
  #   pin:
  #     mcp23017: mcp23017_hub
  #     number: 15
  #     mode: INPUT_PULLUP
  # - platform: gpio
  #   id: esp_sprinkler_controller_mcp23017_int_a
  #   name: "Sprinkler Controller MCP23017 Interrupt A"
  #   pin:
  #     number: GPIO36
  # - platform: gpio
  #   id: esp_sprinkler_controller_mcp23017_int_b
  #   name: "Sprinkler Controller MCP23017 Interrupt B"
  #   pin:
  #     number: GPIO39
  - platform: gpio
    id: esp_sprinkler_controller_motion_detection
    name: "Sprinkler Controller Motion Detection"
    pin:
      number: GPIO27
    on_state:
      then:
        - if:
            condition:
              switch.is_on: esp_sprinkler_controller_display_on_motion
            then:
              - script.execute: display_on
  - platform: gpio
    id: esp_sprinkler_controller_mode_button
    name: "Sprinkler Controller Mode Button"
    pin:
      number: GPIO0
      inverted: true
    on_click:
      min_length: 50ms
      max_length: 500ms
      then:
        - lambda: 'esp_sprinkler::mode_button_click();'
        - component.update: main_lcd
        - script.execute: button_press
  - platform: gpio
    id: esp_sprinkler_controller_encoder_button
    name: "Sprinkler Controller Encoder Button"
    pin:
      number: GPIO2
      inverted: true
    on_click:
      min_length: 50ms
      max_length: 500ms
      then:
        - lambda: 'esp_sprinkler::encoder_button_click();'
        - component.update: main_lcd
        - script.execute: button_press

sensor:
  # Phototransistor ADC sensor
  - platform: adc
    id: adc_sensor_phototransistor
    name: "Sprinkler Controller Phototransistor ADC"
    pin: 32
    attenuation: 11db
    update_interval: 1s
    filters:
      - sliding_window_moving_average:
          window_size: 5
          send_every: 3
          send_first_at: 1
    on_value:
      then:
        - lambda: |-
            const float display_brightness = id(adc_sensor_phototransistor).state / 3.9;
            id(main_lcd)->set_brightness(display_brightness);
  # NTC thermistor ADC sensor
  - platform: adc
    id: adc_sensor_thermistor
    name: "Sprinkler Controller Thermistor ADC"
    pin: 34
    internal: true
    update_interval: 15s
  # NTC thermistor resistance sensor
  - platform: resistance
    id: thermistor_sensor
    name: "Sprinkler Controller NTC Thermistor Resistance"
    sensor: adc_sensor_thermistor
    configuration: DOWNSTREAM
    reference_voltage: 0.85V
    resistor: 10kOhm
    internal: true
  # NTC thermistor sensor
  - platform: ntc
    id: esp_sprinkler_controller_thermistor_temperature
    name: "Sprinkler Controller NTC Thermistor Temperature"
    sensor: thermistor_sensor
    calibration:
      b_constant: 3380
      reference_temperature: 25°C
      reference_resistance: 10kOhm
    filters:
      - sliding_window_moving_average:
          window_size: 5
          send_every: 1
          send_first_at: 1
  # DHT22 sensor
  - platform: dht
    pin: GPIO23
    model: DHT22
    temperature:
      id: esp_sprinkler_controller_dht22_temperature
      name: "Sprinkler Controller DHT22 Temperature"
      filters:
        - offset: -1.2
    humidity:
      id: esp_sprinkler_controller_dht22_humidity
      name: "Sprinkler Controller DHT22 Humidity"
    update_interval: 15s
  # BME280 sensor
  - platform: bme280
    address: 0x76
    temperature:
      id: esp_sprinkler_controller_bme280_temperature
      name: "Sprinkler Controller BME280 Temperature"
      filters:
        - offset: -0.5
    humidity:
      id: esp_sprinkler_controller_bme280_humidity
      name: "Sprinkler Controller BME280 Humidity"
    pressure:
      id: esp_sprinkler_controller_bme280_pressure
      name: "Sprinkler Controller BME280 Pressure"
    update_interval: 15s
  # SHTC3 sensor
  - platform: shtcx
    temperature:
      id: esp_sprinkler_controller_shtcx_temperature
      name: "Sprinkler Controller SHTC3 Temperature"
      filters:
        - offset: -1
    humidity:
      id: esp_sprinkler_controller_shtcx_humidity
      name: "Sprinkler Controller SHTC3 Humidity"
    update_interval: 15s
  # TMP117 sensor
  - platform: tmp117
    id: esp_sprinkler_controller_tmp117_temperature
    name: "Sprinkler Controller TMP117 Temperature"
    filters:
      - offset: -1.25
    update_interval: 15s
  # Encoder sensor
  - platform: rotary_encoder
    id: esp_sprinkler_controller_encoder
    name: "Sprinkler Controller Encoder"
    pin_a: GPIO18
    pin_b: GPIO19
    on_value:
      then:
        - lambda: 'esp_sprinkler::encoder_value_change();'
        - component.update: main_lcd
        - script.execute: button_press

switch:
  # display control
  - platform: template
    id: esp_sprinkler_controller_display
    name: "Sprinkler Controller Display"
    turn_on_action:
      - script.execute: display_on
    turn_off_action:
      - lambda: 'id(main_lcd)->turn_off();'
    lambda: 'return id(main_lcd)->is_on();'
  # display control by motion
  - platform: template
    id: esp_sprinkler_controller_display_on_motion
    name: "Sprinkler Controller Display On Motion"
    optimistic: true
    restore_state: true
  # zone auto-advance -- enables automatic advancing to the next zone until all zone enablers are "off"
  - platform: template
    id: esp_sprinkler_controller_auto_advance
    name: "Sprinkler Controller Auto-Advance"
    optimistic: true
  # zone enablers -- 'on' means a zone will run in the cycle, 'off' means it will not
  - platform: template
    id: esp_sprinkler_controller_zone_1_enable
    name: "Sprinkler Controller Zone 1 Enable"
    optimistic: true
  - platform: template
    id: esp_sprinkler_controller_zone_2_enable
    name: "Sprinkler Controller Zone 2 Enable"
    optimistic: true
  - platform: template
    id: esp_sprinkler_controller_zone_3_enable
    name: "Sprinkler Controller Zone 3 Enable"
    optimistic: true
  - platform: template
    id: esp_sprinkler_controller_zone_4_enable
    name: "Sprinkler Controller Zone 4 Enable"
    optimistic: true
  - platform: template
    id: esp_sprinkler_controller_zone_5_enable
    name: "Sprinkler Controller Zone 5 Enable"
    optimistic: true
  # patch template switches to phyical switches so control is consistent
  - platform: template
    id: esp_sprinkler_controller_zone_1
    name: "Sprinkler Controller Zone 1"
    turn_on_action:
      - lambda: 'esp_sprinkler::start_zone(0);'
      - script.execute: all_zones_off
      - delay: 3s
      - switch.turn_on: esp_sprinkler_controller_triac_zone_1
      - switch.turn_on: esp_sprinkler_controller_triac_master
    turn_off_action:
      - script.execute: all_zones_off
      - lambda: 'esp_sprinkler::stop_zone(0);'
    lambda: 'return id(esp_sprinkler_controller_triac_zone_1).state;'
  - platform: template
    id: esp_sprinkler_controller_zone_2
    name: "Sprinkler Controller Zone 2"
    turn_on_action:
      - lambda: 'esp_sprinkler::start_zone(1);'
      - script.execute: all_zones_off
      - delay: 3s
      - switch.turn_on: esp_sprinkler_controller_triac_zone_2
      - switch.turn_on: esp_sprinkler_controller_triac_master
    turn_off_action:
      - script.execute: all_zones_off
      - lambda: 'esp_sprinkler::stop_zone(1);'
    lambda: 'return id(esp_sprinkler_controller_triac_zone_2).state;'
  - platform: template
    id: esp_sprinkler_controller_zone_3
    name: "Sprinkler Controller Zone 3"
    turn_on_action:
      - lambda: 'esp_sprinkler::start_zone(2);'
      - script.execute: all_zones_off
      - delay: 3s
      - switch.turn_on: esp_sprinkler_controller_triac_zone_3
      - switch.turn_on: esp_sprinkler_controller_triac_master
    turn_off_action:
      - script.execute: all_zones_off
      - lambda: 'esp_sprinkler::stop_zone(2);'
    lambda: 'return id(esp_sprinkler_controller_triac_zone_3).state;'
  - platform: template
    id: esp_sprinkler_controller_zone_4
    name: "Sprinkler Controller Zone 4"
    turn_on_action:
      - lambda: 'esp_sprinkler::start_zone(3);'
      - script.execute: all_zones_off
      - delay: 3s
      - switch.turn_on: esp_sprinkler_controller_triac_zone_4
      - switch.turn_on: esp_sprinkler_controller_triac_master
    turn_off_action:
      - script.execute: all_zones_off
      - lambda: 'esp_sprinkler::stop_zone(3);'
    lambda: 'return id(esp_sprinkler_controller_triac_zone_4).state;'
  - platform: template
    id: esp_sprinkler_controller_zone_5
    name: "Sprinkler Controller Zone 5"
    turn_on_action:
      - lambda: 'esp_sprinkler::start_zone(4);'
      - script.execute: all_zones_off
      - delay: 3s
      - switch.turn_on: esp_sprinkler_controller_triac_zone_5
      - switch.turn_on: esp_sprinkler_controller_triac_master
    turn_off_action:
      - script.execute: all_zones_off
      - lambda: 'esp_sprinkler::stop_zone(4);'
    lambda: 'return id(esp_sprinkler_controller_triac_zone_5).state;'
  - platform: template
    id: esp_sprinkler_controller_master
    name: "Sprinkler Controller Master Valve"
    turn_on_action:
      - lambda: 'esp_sprinkler::start_master();'
      - switch.turn_on: esp_sprinkler_controller_triac_master
    turn_off_action:
      - lambda: 'esp_sprinkler::stop_master();'
      - switch.turn_off: esp_sprinkler_controller_triac_master
      - script.execute: all_zones_off
    lambda: 'return id(esp_sprinkler_controller_triac_master).state;'
  # physical switches
  - platform: gpio
    id: esp_sprinkler_controller_dht22_vcc
    name: "Sprinkler Controller DHT22 Vcc"
    internal: true
    restore_mode: ALWAYS_ON
    pin:
      number: 25
      mode: OUTPUT
  - platform: gpio
    id: esp_sprinkler_controller_thermistor_vcc
    name: "Sprinkler Controller Thermistor Vcc"
    internal: true
    restore_mode: ALWAYS_ON
    pin:
      number: 33
      mode: OUTPUT
  - platform: gpio
    id: esp_sprinkler_controller_mcp23017_reset
    name: "Sprinkler Controller MCP23017 Reset"
    internal: true
    restore_mode: ALWAYS_OFF
    pin:
      number: 4
      mode: OUTPUT
      inverted: true
  - platform: gpio
    id: esp_sprinkler_controller_triac_zone_1
    name: "Sprinkler Controller TRIAC Zone 1"
    internal: true
    pin:
      mcp23017: mcp23017_hub
      number: 0
      mode: OUTPUT
  - platform: gpio
    id: esp_sprinkler_controller_triac_zone_2
    name: "Sprinkler Controller TRIAC Zone 2"
    internal: true
    pin:
      mcp23017: mcp23017_hub
      number: 1
      mode: OUTPUT
  - platform: gpio
    id: esp_sprinkler_controller_triac_zone_3
    name: "Sprinkler Controller TRIAC Zone 3"
    internal: true
    pin:
      mcp23017: mcp23017_hub
      number: 2
      mode: OUTPUT
  - platform: gpio
    id: esp_sprinkler_controller_triac_zone_4
    name: "Sprinkler Controller TRIAC Zone 4"
    internal: true
    pin:
      mcp23017: mcp23017_hub
      number: 3
      mode: OUTPUT
  - platform: gpio
    id: esp_sprinkler_controller_triac_zone_5
    name: "Sprinkler Controller TRIAC Zone 5"
    internal: true
    pin:
      mcp23017: mcp23017_hub
      number: 4
      mode: OUTPUT
  - platform: gpio
    id: esp_sprinkler_controller_triac_zone_6
    name: "Sprinkler Controller TRIAC Zone 6"
    internal: true
    pin:
      mcp23017: mcp23017_hub
      number: 5
      mode: OUTPUT
  - platform: gpio
    id: esp_sprinkler_controller_triac_zone_7
    name: "Sprinkler Controller TRIAC Zone 7"
    internal: true
    pin:
      mcp23017: mcp23017_hub
      number: 6
      mode: OUTPUT
  - platform: gpio
    id: esp_sprinkler_controller_triac_master
    name: "Sprinkler Controller TRIAC Master Valve"
    internal: true
    pin:
      mcp23017: mcp23017_hub
      number: 7
      mode: OUTPUT
  - platform: gpio
    id: esp_sprinkler_controller_relay_1
    name: "Sprinkler Controller Relay 1"
    # internal: true
    pin:
      mcp23017: mcp23017_hub
      number: 8
      mode: OUTPUT
  - platform: gpio
    id: esp_sprinkler_controller_relay_2
    name: "Sprinkler Controller Relay 2"
    # internal: true
    pin:
      mcp23017: mcp23017_hub
      number: 9
      mode: OUTPUT
  - platform: gpio
    id: esp_sprinkler_controller_relay_3
    name: "Sprinkler Controller Relay 3"
    # internal: true
    pin:
      mcp23017: mcp23017_hub
      number: 10
      mode: OUTPUT
  - platform: gpio
    id: esp_sprinkler_controller_to_1
    name: "Sprinkler Controller Test Output 1"
    internal: true
    pin:
      mcp23017: mcp23017_hub
      number: 11
      mode: OUTPUT
  - platform: gpio
    id: esp_sprinkler_controller_to_2
    name: "Sprinkler Controller Test Output 2"
    internal: true
    pin:
      mcp23017: mcp23017_hub
      number: 12
      mode: OUTPUT
  - platform: gpio
    id: esp_sprinkler_controller_to_3
    name: "Sprinkler Controller Test Output 3"
    internal: true
    pin:
      mcp23017: mcp23017_hub
      number: 13
      mode: OUTPUT
  # - platform: gpio
  #   id: esp_sprinkler_controller_to_4
  #   name: "Sprinkler Controller Test Output 4"
  #   internal: true
  #   pin:
  #     mcp23017: mcp23017_hub
  #     number: 14
  #     mode: OUTPUT
  # - platform: gpio
  #   id: esp_sprinkler_controller_to_5
  #   name: "Sprinkler Controller Test Output 5"
  #   internal: true
  #   pin:
  #     mcp23017: mcp23017_hub
  #     number: 15
  #     mode: OUTPUT

# try OpenSansCondensed-Light.ttf
font:
  - file: "Helvetica.ttf"
    id: controller_large
    size: 24
  - file: "Helvetica.ttf"
    id: controller_medium
    size: 18
  - file: "Helvetica.ttf"
    id: controller_small
    size: 11
    # glyphs: '!"%()<>+,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz'
  - file: "Helvetica.ttf"
    id: controller_tiny
    size: 9

color:
  - id: color_mode
    white: 50%
  - id: color_action
    white: 100%
  - id: color_footer
    white: 20%
  - id: color_time
    white: 8%
  - id: color_highlight
    white: 90%
  - id: color_lowlight
    white: 8%

display:
  - platform: ssd1325_spi
    id: main_lcd
    model: "SSD1325 128x64"
    # model: "SSD1327 128x128"
    cs_pin: GPIO15
    dc_pin: GPIO16
    reset_pin: GPIO17
    pages:
      - id: main_screen
        lambda: 'esp_sprinkler::draw_main_screen(&it);'
      - id: setup_screen
        lambda: 'esp_sprinkler::draw_setup_screen(&it);'
